# Generated by Django 4.2.2 on 2023-07-04 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "msg_object",
                    models.CharField(
                        max_length=255, verbose_name="Object of the message"
                    ),
                ),
                ("msg_content", models.TextField(verbose_name="Message content")),
                (
                    "msg_status_sender",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("sent", "sent"),
                            ("bin", "bin"),
                            ("delete", "delete"),
                        ],
                        default="sent",
                        max_length=30,
                        verbose_name="Message status for sender",
                    ),
                ),
                (
                    "msg_status_recipient",
                    models.CharField(
                        choices=[
                            ("unread", "unread"),
                            ("read", "read"),
                            ("bin", "bin"),
                            ("delete", "delete"),
                            ("bin_unread", "bin_unread"),
                            ("delete_unread", "delete_unread"),
                        ],
                        default="unread",
                        max_length=30,
                        verbose_name="Message status for recipient",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender user",
                    ),
                ),
            ],
        ),
    ]
